# Generated by Django 4.2.28 on 2026-02-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(db_index=True, max_length=2000, unique=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Sent Article",
                "verbose_name_plural": "Sent Articles",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Comma-separated list of keywords for article selection (e.g., "ai, agent, mcp").',
            ),
        ),
        migrations.AlterField(
            model_name="newsletterconfig",
            name="config_json",
            field=models.JSONField(
                default=dict,
                help_text='Advanced settings as JSON. Common keys: "email_subject", "dry_run" (bool), "source_weights" (dict of domain:weight).',
            ),
        ),
        migrations.AlterField(
            model_name="newsletterconfig",
            name="send_schedule",
            field=models.CharField(
                help_text='Cron expression (e.g., "0 9 * * *" for daily at 9am, "0 10 * * 1" for Mondays at 10am).',
                max_length=100,
            ),
        ),
    ]
